# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Eric Jinks
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Front-end Web Developer / Sound Designer / Musician / Visual Artist
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ericjinks.com" # the base hostname & protocol for your site
twitter_username: jinksi
github_username:  jinksi

# Build settings
markdown: kramdown
